#!/bin/sh
# encrypt_file
# Does what's on the tin, encrypts files.
FILE="$1"
OPERATION="$2"

if [ "$OPERATION" = "encrypt" ]; then
	gpg --cipher-algo AES256 --symmetric --output - $FILE
elif [ "$OPERATION" = "decrypt" ]; then
	gpg --output - --decrypt $FILE
fi
